Repository FreakPeople/freak-devtoon-back, pull requests merged in 2024-05, with the labels that each got.

#28 refactor: Response 클래스 이름 변경
  src/main/java/yjh/devtoon/bad_words_warning_count/presentation/BadWordsWarningCountController.java
  src/main/java/yjh/devtoon/comment/presentation/CommentController.java
  src/main/java/yjh/devtoon/common/exception/GlobalControllerAdvice.java
  src/main/java/yjh/devtoon/common/response/ApiReponse.java
  src/main/java/yjh/devtoon/cookie_wallet/presentation/CookieWalletController.java
  src/main/java/yjh/devtoon/payment/presentation/CookiePaymentController.java
  src/main/java/yjh/devtoon/payment/presentation/WebtoonPaymentController.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionController.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
  src/main/java/yjh/devtoon/webtoon_viewer/presentation/WebtoonViewerController.java
Labels: 🚀 BE, 🔍 Refactor

#44 refactor: BigDecimal필드를 (원시)값 타입 클래스로 분리
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/domain/CookiePaymentEntity.java
  src/main/java/yjh/devtoon/payment/domain/Price.java
  src/main/java/yjh/devtoon/payment/dto/CookiePaymentDetailDto.java
  src/main/java/yjh/devtoon/payment/dto/response/CookiePaymentRetrieveResponse.java
  src/main/java/yjh/devtoon/payment/presentation/CookiePaymentController.java
  src/test/java/yjh/devtoon/payment/domain/PriceTest.java
  src/test/java/yjh/devtoon/payment/integration/CookiePaymentIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#48 refactor: 도메인 모델 전체에 toString() 메서드 오버라이딩 적용
  src/main/java/yjh/devtoon/bad_words_warning_count/domain/BadWordsWarningCountEntity.java
  src/main/java/yjh/devtoon/comment/domain/CommentEntity.java
  src/main/java/yjh/devtoon/cookie_wallet/domain/CookieWalletEntity.java
  src/main/java/yjh/devtoon/payment/domain/CookiePaymentEntity.java
  src/main/java/yjh/devtoon/payment/domain/Price.java
  src/main/java/yjh/devtoon/payment/domain/WebtoonPaymentEntity.java
  src/main/java/yjh/devtoon/webtoon/domain/WebtoonEntity.java
  src/main/java/yjh/devtoon/webtoon_viewer/domain/WebtoonViewerEntity.java
Labels: 🚀 BE, 🛠 Refactor

#50 refactor: 에러 메시지 문자열 하드코딩을 상수로 변경
  src/main/java/yjh/devtoon/common/utils/ResourceType.java
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/application/WebtoonPaymentService.java
  src/main/java/yjh/devtoon/payment/constant/ErrorMessage.java
  src/main/java/yjh/devtoon/policy/application/PolicyService.java
  src/main/java/yjh/devtoon/policy/domain/factory/PolicyFactory.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/constant/ErrorMessage.java
Labels: 🚀 BE, 🛠 Refactor

#51 refactor: 계산 로직 Calculator enum 클래스로 분리
  src/main/java/yjh/devtoon/payment/domain/Calculator.java
  src/main/java/yjh/devtoon/payment/domain/Price.java
  src/test/java/yjh/devtoon/payment/domain/PriceTest.java
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#53 refactor: aop를 활용한 request 로깅 기능 구현
  build.gradle
  src/main/java/yjh/devtoon/common/aop/LoggingAspect.java
  src/main/java/yjh/devtoon/common/aop/PointcutConfig.java
  src/main/java/yjh/devtoon/common/exception/GlobalControllerAdvice.java
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/policy/application/PolicyService.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
Labels: ✨ Feature, 🚀 BE, 🛠 Refactor

#52 refactor: 쿠키 및 비속어 정책 등록
  src/main/java/yjh/devtoon/policy/application/PolicyService.java
  src/main/java/yjh/devtoon/policy/common/Policy.java
  src/main/java/yjh/devtoon/policy/common/PolicyManager.java
  src/main/java/yjh/devtoon/policy/domain/BadWordsPolicyEntity.java
  src/main/java/yjh/devtoon/policy/domain/CookiePolicyEntity.java
  src/main/java/yjh/devtoon/policy/domain/PolicyFactory.java
  src/main/java/yjh/devtoon/policy/domain/PolicyType.java
  src/main/java/yjh/devtoon/policy/domain/factory/PolicyFactory.java
  src/main/java/yjh/devtoon/policy/dto/request/PolicyCreateRequest.java
  src/main/java/yjh/devtoon/policy/infrastructure/BadWordsPolicyRepository.java
  src/main/java/yjh/devtoon/policy/infrastructure/CookiePolicyRepository.java
  src/main/java/yjh/devtoon/policy/infrastructure/PolicyRepositoryRegistry.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
  src/test/java/yjh/devtoon/policy/integration/PolicyIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#54 refactor: 비즈니스 로직의 return값을 도메인으로 변경
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/dto/CookiePaymentDetailDto.java
  src/main/java/yjh/devtoon/payment/dto/response/CookiePaymentRetrieveResponse.java
  src/main/java/yjh/devtoon/payment/presentation/CookiePaymentController.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionController.java
Labels: 🚀 BE, 🛠 Refactor

#56 fix: 프로모션 테이블 수정
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/domain/DiscountType.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionEntity.java
  src/main/java/yjh/devtoon/promotion/dto/request/PromotionAttributeCreateRequest.java
  src/main/java/yjh/devtoon/promotion/dto/request/PromotionCreateRequest.java
  src/test/java/yjh/devtoon/payment/integration/CookiePaymentIntegrationTest.java
  src/test/java/yjh/devtoon/promotion/application/PromotionServiceTest.java
  src/test/java/yjh/devtoon/promotion/domain/PromotionEntityTest.java
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
Labels: 🔥 Bug, 🚀 BE, 🛠 Refactor, 💯 Test

#58 fix: 프로모션 조회 로직 수정
  src/main/java/yjh/devtoon/bad_words_warning_count/presentation/BadWordsWarningCountController.java
  src/main/java/yjh/devtoon/comment/presentation/CommentController.java
  src/main/java/yjh/devtoon/common/exception/GlobalControllerAdvice.java
  src/main/java/yjh/devtoon/common/response/ApiResponse.java
  src/main/java/yjh/devtoon/cookie_wallet/presentation/CookieWalletController.java
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/presentation/CookiePaymentController.java
  src/main/java/yjh/devtoon/payment/presentation/WebtoonPaymentController.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/dto/response/RetrieveActivePromotionAttributesResponse.java
  src/main/java/yjh/devtoon/promotion/dto/response/RetrieveActivePromotionsResponse.java
  src/main/java/yjh/devtoon/promotion/infrastructure/PromotionAttributeRepository.java
  src/main/java/yjh/devtoon/promotion/infrastructure/PromotionRepository.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionController.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
  src/main/java/yjh/devtoon/webtoon_viewer/presentation/WebtoonViewerController.java
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
Labels: 🔥 Bug, 🚀 BE, 💯 Test

#60 refactor: 쿠키 및 웹툰 미리보기 결제 기능 구현
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/application/WebtoonPaymentService.java
  src/main/java/yjh/devtoon/promotion/domain/AttributeName.java
  src/main/java/yjh/devtoon/promotion/domain/DiscountType.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionAttributeEntity.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionEntity.java
  src/main/java/yjh/devtoon/webtoon/application/WebtoonService.java
  src/main/java/yjh/devtoon/webtoon/constant/ErrorMessage.java
  src/main/java/yjh/devtoon/webtoon/domain/Genre.java
  src/main/java/yjh/devtoon/webtoon/domain/WebtoonEntity.java
  src/main/java/yjh/devtoon/webtoon/dto/request/WebtoonCreateRequest.java
  src/main/java/yjh/devtoon/webtoon_viewer/domain/WebtoonViewerEntity.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor

#62 refactor: 웹툰 미리보기 결제 로직 개선
  src/main/java/yjh/devtoon/payment/application/WebtoonPaymentService.java
  src/main/java/yjh/devtoon/promotion/domain/AttributeName.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionAttributeEntity.java
  src/main/java/yjh/devtoon/promotion/domain/attribute/Attribute.java
  src/main/java/yjh/devtoon/promotion/domain/attribute/Author.java
  src/main/java/yjh/devtoon/promotion/domain/attribute/Genre.java
  src/main/java/yjh/devtoon/promotion/domain/promotion/CashPromotion.java
  src/main/java/yjh/devtoon/promotion/domain/promotion/CookiePromotion.java
  src/main/java/yjh/devtoon/promotion/domain/promotion/Promotion.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionController.java
  src/main/java/yjh/devtoon/webtoon/domain/Genre.java
  src/main/java/yjh/devtoon/webtoon/domain/WebtoonEntity.java
  src/test/java/yjh/devtoon/comment/integration/CommentIntegrationTest.java
  src/test/java/yjh/devtoon/payment/integration/WebtoonPaymentIntegrationTest.java
  src/test/java/yjh/devtoon/webtoon/domain/WebtoonEntityTest.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor

#64 refactor: 프로모션 등록 및 조회에 Caffeine 로컬 캐시 적용 및 성능 최적화
  build.gradle
  src/main/java/yjh/devtoon/common/config/CacheConfig.java
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/promotion/application/PromotionCacheService.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionEntity.java
  src/main/java/yjh/devtoon/promotion/infrastructure/PromotionRepository.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionCacheController.java
  src/main/resources/application-dev.yaml
  src/main/resources/data.sql
  src/test/java/yjh/devtoon/promotion/application/PromotionServiceTest.java
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor
