Repository FreakPeople/freak-devtoon-back, pull requests merged in 2024-07, with the labels that each got.

#110 feat: 웹툰 이미지 등록 기능 구현
  .gitignore
  src/main/java/yjh/devtoon/webtoon/application/WebtoonService.java
  src/main/java/yjh/devtoon/webtoon/domain/WebtoonEntity.java
  src/main/java/yjh/devtoon/webtoon/infrastructure/ImageRepository.java
  src/main/java/yjh/devtoon/webtoon/infrastructure/LocalImageRepository.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
  src/main/resources/application-dev.yaml
  src/test/java/yjh/devtoon/webtoon/domain/WebtoonEntityTest.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: ✨ Feature, 🚀 BE

#112 refactor: security config 설정 변경
  src/main/java/yjh/devtoon/common/config/SecurityConfig.java
Labels: 🚀 BE, 🛠 Refactor

#114 refactor: 웹툰 응답 형식 변경
  src/main/java/yjh/devtoon/webtoon/dto/response/WebtoonResponse.java
Labels: 🚀 BE, 🛠 Refactor

#118 Refactor/#117
  src/main/java/yjh/devtoon/common/config/WebConfig.java
  src/main/resources/data.sql
Labels: 🚀 BE, 🛠 Refactor

#120 feat: 웹툰 이미지 조회 기능 구현
  src/main/java/yjh/devtoon/common/config/SecurityConfig.java
  src/main/java/yjh/devtoon/webtoon/application/WebtoonService.java
  src/main/java/yjh/devtoon/webtoon/infrastructure/ImageRepository.java
  src/main/java/yjh/devtoon/webtoon/infrastructure/LocalImageRepository.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
Labels: ✨ Feature, 🚀 BE

#121 Refactor/#93
  src/main/java/yjh/devtoon/comment/application/CommentService.java
  src/main/java/yjh/devtoon/comment/domain/CommentEntity.java
  src/main/java/yjh/devtoon/comment/dto/reponse/CommentResponse.java
  src/main/java/yjh/devtoon/comment/dto/request/CommentCreateRequest.java
  src/main/java/yjh/devtoon/comment/infrastructure/BadWordsDetector.java
  src/test/java/yjh/devtoon/comment/domain/CommentEntityTest.java
  src/test/java/yjh/devtoon/comment/integration/CommentIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor

#124 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE

#125 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE

#126 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE

#128 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE

#130 feat: 나의 웹툰 조회 기능 구현
  src/main/java/yjh/devtoon/webtoon/application/WebtoonService.java
  src/main/java/yjh/devtoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: ✨ Feature, 🚀 BE

#131 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs

#133 docs: 리드미 API명세서 업데이트
  README.md
Labels: 📚 Docs

#134 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE

#139 refactor: 통합 테스트의 기간 의존성 제거
  src/test/java/yjh/devtoon/policy/integration/PolicyIntegrationTest.java
  src/test/java/yjh/devtoon/promotion/application/PromotionServiceTest.java
  src/test/java/yjh/devtoon/promotion/domain/PromotionEntityTest.java
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
Labels: 🔥 Bug, 💯 Test

#142 refactor: SQL 스크립트 날짜 처리 방식 개선
  src/main/resources/data.sql
Labels: 🛠 Refactor

#143 docs: 리드미 업데이트
  README.md
Labels: 📚 Docs, 🚀 BE
