Repository FreakPeople/freak-devtoon-back, pull requests merged in 2024-06, with the labels that each got.

#66 refactor: 프로모션 조회 캐시 적용
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/application/WebtoonPaymentService.java
  src/main/java/yjh/devtoon/policy/infrastructure/CookiePolicyRepository.java
  src/main/java/yjh/devtoon/promotion/domain/PromotionAttributeEntity.java
  src/main/resources/data.sql
  src/test/java/yjh/devtoon/payment/integration/CookiePaymentIntegrationTest.java
Labels: 🚀 BE, 🛠 Refactor

#68 refactor: 프로모션 조회에 Redis 캐시 적용 및 성능 테스트
  build.gradle
  src/main/java/yjh/devtoon/common/config/RedisConfig.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionCacheController.java
  src/main/resources/application-dev.yaml
  src/main/resources/data.sql
  src/test/java/yjh/devtoon/payment/integration/WebtoonPaymentIntegrationTest.java
  src/test/java/yjh/devtoon/promotion/application/PromotionServiceTest.java
Labels: 🚀 BE, 🛠 Refactor

#70 refactor: 프로모션 조회에 로컬 캐시 사용으로 변경
  build.gradle
  src/main/java/yjh/devtoon/common/config/RedisConfig.java
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/resources/application-dev.yaml
  src/test/java/yjh/devtoon/payment/integration/CookiePaymentIntegrationTest.java
  src/test/java/yjh/devtoon/payment/integration/WebtoonPaymentIntegrationTest.java
Labels: 🔥 Bug, 🚀 BE, 🛠 Refactor, 💯 Test

#72 feat: 웹툰 전체 조회 기능 구현
  src/main/java/yjh/devtoon/webtoon/application/WebtoonService.java
  src/main/java/yjh/devtoon/webtoon/presentation/WebtoonController.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: ✨ Feature, 🚀 BE

#74 feat: CORS 설정 추가
  src/main/java/yjh/devtoon/common/config/WebConfig.java
Labels: ✨ Feature, 🚀 BE

#76 refactor: 웹툰 응답 형식 변경
  src/main/java/yjh/devtoon/webtoon/dto/response/WebtoonResponse.java
Labels: 🚀 BE, 🛠 Refactor

#78 refactor: 웹툰 뷰어 응답 형식 변경
  src/main/java/yjh/devtoon/webtoon_viewer/dto/response/WebtoonViewerResponse.java
Labels: 🚀 BE, 🛠 Refactor

#83 refactor: 엔티티를 찾는 로직과 ID를 가져오는 로직을 분리
  src/main/java/yjh/devtoon/payment/application/CookiePaymentService.java
  src/main/java/yjh/devtoon/payment/application/WebtoonPaymentService.java
Labels: 🚀 BE, 🛠 Refactor

#84 feat: 쿠키 정책 조회 API구현
  src/main/java/yjh/devtoon/policy/application/PolicyService.java
  src/main/java/yjh/devtoon/policy/constant/ErrorMessage.java
  src/main/java/yjh/devtoon/policy/dto/response/RetrieveActivePoliciesResponse.java
  src/main/java/yjh/devtoon/policy/dto/response/RetrieveCookiePolicyResponse.java
  src/main/java/yjh/devtoon/policy/infrastructure/CookiePolicyRepository.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
Labels: ✨ Feature, 🚀 BE

#86 feat: 특정 웹툰의 모든 댓글 조회 기능 구현
  src/main/java/yjh/devtoon/comment/application/CommentService.java
  src/main/java/yjh/devtoon/comment/infrastructure/CommentRepository.java
  src/main/java/yjh/devtoon/comment/presentation/CommentController.java
  src/test/java/yjh/devtoon/comment/integration/CommentIntegrationTest.java
Labels: ✨ Feature, 🚀 BE

#87 feat: 비속어 정책 조회 API구현
  src/main/java/yjh/devtoon/policy/application/PolicyService.java
  src/main/java/yjh/devtoon/policy/dto/response/RetrieveBadWordsPolicyResponse.java
  src/main/java/yjh/devtoon/policy/infrastructure/BadWordsPolicyRepository.java
  src/main/java/yjh/devtoon/policy/presentation/PoilcyController.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🚀 BE

#88 feat: 종료된 모든 프로모션 조회 API구현
  src/main/java/yjh/devtoon/promotion/application/PromotionService.java
  src/main/java/yjh/devtoon/promotion/dto/response/RetrieveEndedPromotionsResponse.java
  src/main/java/yjh/devtoon/promotion/infrastructure/PromotionRepository.java
  src/main/java/yjh/devtoon/promotion/presentation/PromotionController.java
  src/main/resources/data.sql
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
Labels: ✨ Feature, 🚀 BE, 💯 Test

#96 feat: 회원 권한 기능 구현
  src/main/java/yjh/devtoon/member/application/MemberService.java
  src/main/java/yjh/devtoon/member/domain/Authority.java
  src/main/java/yjh/devtoon/member/domain/MemberEntity.java
  src/main/java/yjh/devtoon/member/domain/Role.java
  src/main/resources/data.sql
  src/test/java/yjh/devtoon/bad_words_warning_count/domain/BadWordsWarningCountEntityTest.java
  src/test/java/yjh/devtoon/cookie_wallet/domain/CookieWalletEntityTest.java
  src/test/java/yjh/devtoon/member/domain/MemberEntityTest.java
Labels: ✨ Feature, 🚀 BE

#97 feat: 로그인 기능 구현
  build.gradle
  src/main/java/yjh/devtoon/auth/application/CustomUserDetailsService.java
  src/main/java/yjh/devtoon/auth/dto/request/LoginRequest.java
  src/main/java/yjh/devtoon/auth/dto/response/TokenReponse.java
  src/main/java/yjh/devtoon/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/yjh/devtoon/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/yjh/devtoon/auth/jwt/JwtFilter.java
  src/main/java/yjh/devtoon/auth/jwt/JwtSecurityConfig.java
  src/main/java/yjh/devtoon/auth/jwt/TokenProvider.java
  src/main/java/yjh/devtoon/auth/presentation/AuthController.java
  src/main/java/yjh/devtoon/auth/util/SecurityUtil.java
  src/main/java/yjh/devtoon/common/config/SecurityConfig.java
  src/main/java/yjh/devtoon/member/application/MemberService.java
  src/main/java/yjh/devtoon/member/domain/Authority.java
  src/main/java/yjh/devtoon/member/domain/Role.java
  src/main/resources/application-dev.yaml
  src/test/java/yjh/devtoon/auth/integration/AuthControllerTest.java
  src/test/java/yjh/devtoon/bad_words_warning_count/integration/BadWordsWarningIntegrationTest.java
  src/test/java/yjh/devtoon/comment/integration/CommentIntegrationTest.java
  src/test/java/yjh/devtoon/cookie_wallet/integration/CookieWalletIntegrationTest.java
  src/test/java/yjh/devtoon/member/integration/MemberIntegrationTest.java
  src/test/java/yjh/devtoon/payment/integration/CookiePaymentIntegrationTest.java
  src/test/java/yjh/devtoon/payment/integration/WebtoonPaymentIntegrationTest.java
  src/test/java/yjh/devtoon/policy/integration/PolicyIntegrationTest.java
  src/test/java/yjh/devtoon/promotion/integration/PromotionIntegrationTest.java
  src/test/java/yjh/devtoon/webtoon/integration/WebtoonIntegrationTest.java
Labels: ✨ Feature, 🚀 BE

#99 feat: ci 스크립트 작성
  .github/workflows/deploy.yaml
  src/test/resources/application-test.yaml
Labels: ✨ Feature, 🚀 BE

#100 test: ci_test
  README.md
Labels: 🚀 BE, 💯 Test

#102 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#103 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#104 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#105 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#106 #test ci
  .github/workflows/deploy.yaml
  README.md
Labels: 🚀 BE, 💯 Test

#107 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#108 test: ci_test
  .github/workflows/deploy.yaml
Labels: 🚀 BE, 💯 Test

#109 test: ci_test
  README.md
Labels: 🚀 BE, 💯 Test
